Write a Python program that checks a simple authentication system. The program verifies the provided username and password against predefined usernames and passwords by using boolean checks.

In [2]:
import getpass

In [1]:
username = "crest123"
password = "crest@123"

In [3]:
while True:
    user = input("Enter the Username")
    pw = getpass.getpass("Enter the Password")
    if username == user and password == pw:
        print("Authentication Successfull!!")
        break
    print("Incorrect Username or Password!!")

Enter the Username crest123
Enter the Password ········


Incorrect Username or Password!!


Enter the Username crest123
Enter the Password ········


Authentication Successfull!!


Write a Python function that replaces all occurrences of a substring in a string with another substring. Returns None if the original string is empty.

In [5]:
s1 = "Hello Jeet"
s2 = ""
sub1 = "Jeet"
sub2 = "Jay"

In [9]:
def fun(s, sub1, sub2):
    if s:
        s = s.replace(sub1,sub2)
        return s
    else:
        return None

In [10]:
res = fun(s1, sub1, sub2)
print(s1)
if res:
    print(res)
else:
    print("String is empty")

Hello Jeet
Hello Jay


In [11]:
res = fun(s2, sub1, sub2)
print(s2)
if res:
    print(res)
else:
    print("String is empty")


String is empty


Write a Python program to convert a given string to bytes using different encodings like UTF-8, UTF-16, ASCII etc.

In [12]:
def convert_to_bytes(input_string, encoding):
    try:
        encoded_bytes = input_string.encode(encoding)
        return encoded_bytes
    except Exception as e:
        print("Error:", e)
        return None

def main():
    try:
        input_string = "Python"
        
        encodings = ["utf-8", "utf-16", "ascii"]
        for encoding in encodings:
            encoded_bytes = convert_to_bytes(input_string, encoding)
            if encoded_bytes is not None:
                print(f"Encoding: {encoding.upper()}")
                print("Original String:", input_string)
                print("Encoded Bytes:", encoded_bytes)
                print("Decoded String:", encoded_bytes.decode(encoding))
                print("=" * 40)
    except Exception as e:
        print("An error occurred:", e)

if __name__ == "__main__":
    main()


Encoding: UTF-8
Original String: Python
Encoded Bytes: b'Python'
Decoded String: Python
Encoding: UTF-16
Original String: Python
Encoded Bytes: b'\xff\xfeP\x00y\x00t\x00h\x00o\x00n\x00'
Decoded String: Python
Encoding: ASCII
Original String: Python
Encoded Bytes: b'Python'
Decoded String: Python


In [52]:
x = bytes('python', encoding = 'utf-8')

In [53]:
x

b'python'

In [54]:
for i in x:
    print(i)

112
121
116
104
111
110


In [62]:
x.append(1)

AttributeError: 'bytes' object has no attribute 'append'

In [56]:
y = bytearray('hello', 'utf-8')

In [57]:
y

bytearray(b'hello')

In [58]:
for i in y:
    print(i)

104
101
108
108
111


In [60]:
y.append(1)

In [61]:
y

bytearray(b'hello\x01')

Write a  Python function that converts a bytearray to a bytes object.

In [51]:
def bytearray_to_bytes(bytearray_obj):
    bytes_obj = bytes(bytearray_obj)
    return bytes_obj

def main():
    try:
        original_bytearray = bytearray([12, 51, 10, 15, 95, 102, 132, 117])
        
        bytes_result = bytearray_to_bytes(original_bytearray)
        
        print("Original Bytearray:", original_bytearray)
        print("Bytes Object:", bytes_result)
        print("Decoded String:", bytes_result.decode("utf-8"))
    except Exception as e:
        print("An error occurred:", e)

if __name__ == "__main__":
    main()

Original Bytearray: bytearray(b'\x0c3\n\x0f_f\x84u')
Bytes Object: b'\x0c3\n\x0f_f\x84u'
An error occurred: 'utf-8' codec can't decode byte 0x84 in position 6: invalid start byte


memoryview

In [67]:
def main():
    try:
        data = b"Python Exercises!"
        # Create memory view on data
        mem_data  = memoryview(data)        
        print("Memory View Length:", len(mem_data))
        # Print first 8 bytes
        print("First 8 Bytes:", mem_data[:8])
    except Exception as e:
        print("An error occurred:", e)

if __name__ == "__main__":
    main()


Memory View Length: 17
First 8 Bytes: <memory at 0x000001C5302E3340>


In [68]:
byte_array = bytearray('XYZ', 'utf-8')
print('Before update:', byte_array)

mem_view = memoryview(byte_array)

mem_view[2] = 74
print('After update:', byte_array)


Before update: bytearray(b'XYZ')
After update: bytearray(b'XYJ')


 Write a Python program that creates a memory view from a list of integers and print the hex values of each element.

In [69]:
def test(memory_view):
    for element in memory_view:
        print(hex(element))

def main():
    nums = [8, 16, 42, 92, 128]
    print("Original list values:",nums)

    memory_view = memoryview(bytearray(nums))

    print("Hex Values of said list elements:")
    test(memory_view)

if __name__ == "__main__":
    main()


Original list values: [8, 16, 42, 92, 128]
Hex Values of said list elements:
0x8
0x10
0x2a
0x5c
0x80


Write a Python program that generates a frozenset containing the squares of all odd numbers from 1 to 15 using set comprehension.

In [72]:
fs = frozenset({x**2 for x in range(1,16) if x%2==1})

In [73]:
fs

frozenset({1, 9, 25, 49, 81, 121, 169, 225})

Write a Python program that defines a NamedTuple named "Car" with fields 'make', 'model', 'year', and 'engine' (a NamedTuple representing engine details). Create an instance of the "Car" NamedTuple and print its attributes.

In [74]:
from collections import namedtuple

In [80]:
Car = namedtuple('Car',['make', 'model', 'year', 'engine'])

In [81]:
Engine = namedtuple('Engine', ['type', 'cylinders'])

In [82]:
car

__main__.Car

In [83]:
engine

__main__.Engine

In [84]:
e1 = Engine(type='1.5L', cylinders=4)

In [85]:
c1 = Car(make='Honda', model='City', year=2020, engine=e1)

In [86]:
c1

Car(make='Honda', model='City', year=2020, engine=Engine(type='1.5L', cylinders=4))

In [87]:
e1

Engine(type='1.5L', cylinders=4)

In [89]:
c1.make

'Honda'

In [91]:
c1.engine.type

'1.5L'

OrderedDict

In [93]:
from collections import OrderedDict

In [101]:
print("This is a Dict:\n")
d = {}
d['b'] = 2
d['a'] = 1
d['c'] = 3
d['d'] = 4

for key, value in d.items():
    print(key, value)

print("\nThis is an Ordered Dict:\n")
od = OrderedDict()
od['b'] = 2
od['a'] = 1
od['c'] = 3
od['d'] = 4

for key, value in od.items():
    print(key, value)

This is a Dict:

b 2
a 1
c 3
d 4

This is an Ordered Dict:

b 2
a 1
c 3
d 4


In [102]:
od

OrderedDict([('b', 2), ('a', 1), ('c', 3), ('d', 4)])

In [103]:
d

{'b': 2, 'a': 1, 'c': 3, 'd': 4}

Write a Python function that takes a list of words and returns an OrderedDict where keys are the words and values are the lengths of the words.

In [104]:
words = ["Red", "Green", "Pink", "White", "Orange"]

In [105]:
od = OrderedDict()
for w in words:
    od[w] = len(w)

od

OrderedDict([('Red', 3),
             ('Green', 5),
             ('Pink', 4),
             ('White', 5),
             ('Orange', 6)])

Write a Python program that creates a 'Counter' for a list of items and uses dictionary-style access to update the count of specific items.

In [106]:
from collections import Counter


items = ['Red', 'Green', 'Black', 'Black', 'Red', 'Red', 'Orange', 'Pink', 'Pink', 'Red', 'White']
    
counter = Counter(items)
    
print("Original Counter:")
print(counter)
    
counter['Red'] += 2
counter['Orange'] -= 1
    
print("\nUpdated Counter:")
print(counter)

Original Counter:
Counter({'Red': 4, 'Black': 2, 'Pink': 2, 'Green': 1, 'Orange': 1, 'White': 1})

Updated Counter:
Counter({'Red': 6, 'Black': 2, 'Pink': 2, 'Green': 1, 'White': 1, 'Orange': 0})


Ellipses or ...

In [107]:
# importing numpy
import numpy as np

array = np.random.rand(2, 2, 2, 2)
print(array[..., 0])
print(array[Ellipsis, 0])


[[[0.88379295 0.78940168]
  [0.44971315 0.15330181]]

 [[0.97363601 0.68601103]
  [0.78296392 0.7913071 ]]]
[[[0.88379295 0.78940168]
  [0.44971315 0.15330181]]

 [[0.97363601 0.68601103]
  [0.78296392 0.7913071 ]]]


In [108]:
def foo(x = ...):
	return x

print(foo)

<function foo at 0x000001C52FA97880>


In [110]:
def foo(x = ...):
	...

print(foo)

<function foo at 0x000001C530425300>


In [111]:
# Argument type is assumed as type: Any
def foo(x: ...) -> None:
              ...

In [112]:
type(foo)

function

Write a Python program that creates a custom class with an 'init' method. Use 'ellipsis' to indicate that some attributes may be added dynamically.

In [113]:
class MyClass:
    def __init__(self, attribute1, attribute2, attribute3, attribute4=...):
        self.attribute1 = attribute1
        self.attribute2 = attribute2
        self.attribute3 = attribute3
        self.attribute4 = attribute4

    def set_attribute4(self, value):
        self.attribute4 = value

obj = MyClass("Red", "Green", "White")

print("Attribute 1:", obj.attribute1)
print("Attribute 2:", obj.attribute2)
print("Attribute 3:", obj.attribute3)
print("Attribute 4:", obj.attribute4)  # Attribute 4 is represented by '...'

# Dynamically add a value to attribute3
obj.set_attribute4("Orange")

# Access and print the modified attribute3
print("Modified Attribute 4:", obj.attribute4)


Attribute 1: Red
Attribute 2: Green
Attribute 3: White
Attribute 4: Ellipsis
Modified Attribute 4: Orange
